# Generated by Django 4.1.4 on 2023-01-11 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "event_status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("INPROGRESS", "Inprogress"),
                            ("FINISHED", "Finished"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="CREATED",
                        max_length=100,
                        verbose_name="Event Status",
                    ),
                ),
                ("attendees", models.IntegerField(default=0)),
                ("event_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "contract",
                    models.OneToOneField(
                        limit_choices_to={"is_signed": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="contracts.contract",
                    ),
                ),
                (
                    "support_contact",
                    models.ForeignKey(
                        limit_choices_to={"team": "SUPPORT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
