# Generated by Django 4.1.4 on 2022-12-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANAGEMENT", "MANAGEMENT"),
                    ("SALES", "SALES"),
                    ("SUPPORT", "SUPPORT"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
