# Generated by Django 4.1.4 on 2022-12-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("MANAGEMENT", "MANAGEMENT"),
                    ("SALES", "SALES"),
                    ("SUPPORT", "SUPPORT"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
    ]
