# Generated by Django 4.1.4 on 2022-12-27 23:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_team"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sales_member", "sales_member"),
                    ("management_member", "management_member"),
                    ("support_member", "support_member"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
