# Generated by Django 4.1.4 on 2022-12-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_team_user_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="group",
            new_name="team",
        ),
    ]
